INPUT_DATA_DIR = "data/"
OUTPUT_DATA_DIR = "output/"
DEFAULT_INPUT_FILENAME = "ad_views.csv"
RECOMMENDATIONS_CSV_FILENAME = "ad_cost_recommendations.csv"
RECOMMENDATIONS_JSON_FILENAME = "ad_cost_recommendations.json"

COST_VS_VIEWS_PLOT_FILENAME = "cost_vs_views.png"
COST_DISTRIBUTION_PLOT_FILENAME = "cost_distribution.png"

SATURATION_VIEW_COUNT = 10
BASE_AD_COST = 1.00
COST_DECAY_RATE = 0.1

NUM_RECORDS_TO_GENERATE = 500
NUM_USERS = 5
NUM_ADS = 10
